# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mccotter-net-ui:
    image: mccotter-net-ui
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
